# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
   build:
    docker:
      - image: circleci/golang:1.13
        environment: 
          - GO111MODULE=on
          - GOLANG_LINT_VERSION=v1.27.0
          - COVERALLS_TOKEN=bO2QMP83jVaKiAOxWnsLZw2Wcp07cV99Q

    working_directory: /go/src/github.com/kiegroup/kogito-cloud-operator
    steps:
      - run: go get -u golang.org/x/lint/golint
      - run: go get github.com/mattn/goveralls
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin $GOLANG_LINT_VERSION
      - checkout
      - run: go mod tidy
      - run: go fmt ./...
      - run: go vet ./...
      - run: golangci-lint run ./...
      - run: ./hack/go-lint.sh
      - run: go test ./...  -p=1  -coverprofile=coverage.out
      - run: goveralls -coverprofile=coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
   test:
    docker:
       - image: circleci/golang:1.13
         environment:
           - GO111MODULE=on
           - GOLANG_LINT_VERSION=v1.27.0
           - COVERALLS_TOKEN=bO2QMP83jVaKiAOxWnsLZw2Wcp07cV99Q
    working_directory: /go/src/github.com/kiegroup/kogito-cloud-operator
    steps:
      - checkout
      - run: go get golang.org/x/tools/cmd/cover
      - run: go get github.com/mattn/goveralls
      - run: go test ./cmd/... -p=1 -coverprofile=coverage.out
      - run: goveralls -coverprofile=coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN

workflows:
      version: 2
      build_and_test:
        jobs:
          - build
          - test