# permissions for end users to edit kogitomgmtconsoles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kogitomgmtconsole-editor-role
rules:
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitomgmtconsoles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitomgmtconsoles/status
  verbs:
  - get
