# permissions for end users to view kogitomgmtconsoles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kogitomgmtconsole-viewer-role
rules:
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitomgmtconsoles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitomgmtconsoles/status
  verbs:
  - get
