# permissions for end users to edit kogitojobsservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kogitojobsservice-editor-role
rules:
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitojobsservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitojobsservices/status
  verbs:
  - get
