---
## used for defining the labels to put on PR on various events

labels:
  - paths:
      - cmd/**
    labels:
      - cli
  - paths:
      - pkg/**
    labels:
      - operator
  - paths:
      - test/**
    labels:
      - 'bdd-tests 🧪'
  - paths:
      - Jenkinsfile
    labels:
      - CI/CD
default:
  - 'needs review :mag:'
