---
#Inside the files list, mention the file name or the directory name inside which if anything changes
#pipeline needs to be run.
#for now we don't have support for wild cards
#though you can define the entire directories or sub-directories to ignore
# for eg: to trigger on change in /pkg/hack/ directory just add that to the list below

files:
  - Jenkinsfile
  - test/
  - cmd/
  - pkg/
