---
## define the list of reviewers here that will be asked to review the PR once it opened or changed
# Please right the username, it is case sensitive so please right exactly the username on github
#

review:
  - paths:
      - cmd/
      - pkg/
    reviewers:
      - Kaitou786
      - Kevin-Mok
  - paths:
      - test/
    reviewers:
      - Kaitou786
  - paths:
      - Jenkinsfile
    reviewers:
      - Kevin-Mok
default:
  - Kaitou786