name: Kogito Operator Commenter for jenkins
on:
  pull_request:
    paths:
      - 'pkg/**'
      - 'cmd/**'
      - 'test/**'
    branches:
      - master
jobs:
  comment:
    name: Comment
      runs-on: ubuntu-latest
      steps:
        - name: comment PR
          uses: unsplash/comment-on-pr@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            msg: "Jenkins, test this"
