name: Kogito Operator Integration Checks
on:
  pull_request:
  push:
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "CONTRIBUTING.md"
      - "examples/**"
      - "LICENSE"
      - "LICENSE_NOTICE"
      - "Makefile"
      - ".github/ISSUE_TEMPLATE/**"
    branches:
      - master
env:
  GO_VERSION: 1.14
jobs:
  olm_tests:
    name: Olm Integration Test
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: operator-test
      KIND_VERSION: v0.8.1
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Go mod
        run: go mod tidy
      - name: Install Operator SDK
        run: ./hack/ci/install-operator-sdk.sh
      - name: Install kind
        run: ./hack/ci/install-kind.sh
      - name: start kind
        run: ./hack/ci/start-kind.sh
      - name: Generate Manifests
        run: ./hack/generate-manifests.sh
      - name: Build operator-image
        env:
          BUILDER: docker
        run: ./hack/go-build.sh
      - name: Load Operator Image
        run: ./hack/ci/load-operator-image.sh
      - name: Run Operator OLM Integration Test
        run: ./hack/ci/operator-olm-test.sh